export { db } from './client.js'
export * as schema from './schema/index.js'
export { withTenant } from './rls.js'
export type { Tx } from './rls.js'
export { resolvePermissions } from './permissions.js'
export { listRoles, createRole, updateRole, deleteRole } from './roles-queries.js'
export type { RoleWithDetails } from './roles-queries.js'
export { listUsers, getUserDetail, setUserRoles, setUserOverrides } from './users-queries.js'
export type { UserWithRoles, UserDetail } from './users-queries.js'
